<a href="https://colab.research.google.com/github/BhavanaNannuru/Fundamentals-of-Data-science/blob/main/numpy_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [5]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
print(np.__version__)

1.23.5


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
print(np.array(42))
print()
print(np.array([1,2]))
print()
print(np.array([[1,2],[2,3]]))
print()
print(np.array([[[1,2,3],[2,3,4]],[[2,4,5],[1,4,5]]]))

42

[1 2]

[[1 2]
 [2 3]]

[[[1 2 3]
  [2 3 4]]

 [[2 4 5]
  [1 4 5]]]


In [14]:
arr=np.array((1,2,3))
print(arr.ndim)

1


In [17]:
print(arr[0])
print(arr[-1])

1
3


In [21]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,2])
arr=np.array([[[1,2,3],[2,3,4]],[[2,4,5],[1,4,5]]])
print(arr[1,1])
print(arr[1,1,-1])

6
[1 4 5]
5


In [24]:
arr=np.array((1,2,3))
print(arr)
print(arr[0:])
print(arr[:-1])
print(arr[:])
print(arr[1:3])

[1 2 3]
[1 2 3]
[1 2]
[1 2 3]
[2 3]


In [28]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print()
print(arr[0:2,2])
print(arr[0:1,:-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[3 8]
[[1 2 3 4]]


In [33]:
arr=np.array([1,2,3])
print(arr)
print(arr.dtype)
arr= np.array([1,'2',3])
print(arr)
print(arr.dtype)
arr=np.array([1.2,34,5,23.67])
print(arr)
print(arr.dtype)
arr=arr.astype(int)
print(arr)
print(arr.dtype)
print()
arr=arr.astype('i')
print(arr)
print(arr.dtype)

arr=arr.astype(bool)
print(arr)
print(arr.dtype)

[1 2 3]
int64
['1' '2' '3']
<U21
[ 1.2  34.    5.   23.67]
float64
[ 1 34  5 23]
int64

[ 1 34  5 23]
int32
[ True  True  True  True]
bool


In [35]:
arr=np.array([2,4,86,2,3])
print(arr)
print(arr.dtype)
x=arr.copy()
print(x)
arr[0]=7896
print(x)
print(arr)

[ 2  4 86  2  3]
int64
[ 2  4 86  2  3]
[ 2  4 86  2  3]
[7896    4   86    2    3]


In [41]:
arr=np.array([2,4,86,2,3])
print(arr)
print(arr.dtype)
x=arr.view()
print(x)
arr[0]=7896
print(x)
print(arr)
print()
x[1]=0
print(x)
print(arr)

[ 2  4 86  2  3]
int64
[ 2  4 86  2  3]
[7896    4   86    2    3]
[7896    4   86    2    3]

[7896    0   86    2    3]
[7896    0   86    2    3]


In [54]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
x=arr.copy()
print(x.base)
x[1]=0
print(x)
print(x.base)

y=arr.view()
print()
print(y.base)

[1 2 3 4 5]
(5,)
None
[1 0 3 4 5]
None

[1 2 3 4 5]


In [47]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [50]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)
print(arr[-1])

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
[[[[1 2 3 4]]]]


In [58]:
arr=np.array([1,2,3,4,5,6,7,8,90,12,24,21,56,34,67])
print(arr)
print(arr.dtype)
print(arr.shape)
arr=arr.reshape(5,3)
print(arr)
print(arr.shape)
print()
print()
arr=np.array([1,2,3,4,5,6,7,8,90,12,24,21,56,34,67])
print(arr)
print(arr.shape)
arr = arr.reshape(3,5,1)
print(arr)
print(arr.shape)
print(arr.dtype)
arr=arr.astype('i')
print(arr)
print(arr.shape)
print(arr.dtype)


[ 1  2  3  4  5  6  7  8 90 12 24 21 56 34 67]
int64
(15,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 90]
 [12 24 21]
 [56 34 67]]
(5, 3)


[ 1  2  3  4  5  6  7  8 90 12 24 21 56 34 67]
(15,)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [90]
  [12]]

 [[24]
  [21]
  [56]
  [34]
  [67]]]
(3, 5, 1)
int64
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [90]
  [12]]

 [[24]
  [21]
  [56]
  [34]
  [67]]]
(3, 5, 1)
int32


In [63]:
arr=np.array([1,2,3,4,5,6,7,8,90,12,24,21,56,34,67])
print(arr)
x=arr.reshape(5,3)
print(x.base)
x[0]=[0,9,0]
print(x)
print(arr)
x=x.reshape(-1)
print(x)
print(x.shape)
x=x.reshape(3,-1)
print(x)
print(x.shape)
x[0][1]=90809
print(arr)
print(x)
print(x.reshape(-1))

[ 1  2  3  4  5  6  7  8 90 12 24 21 56 34 67]
[ 1  2  3  4  5  6  7  8 90 12 24 21 56 34 67]
[[ 0  9  0]
 [ 4  5  6]
 [ 7  8 90]
 [12 24 21]
 [56 34 67]]
[ 0  9  0  4  5  6  7  8 90 12 24 21 56 34 67]
[ 0  9  0  4  5  6  7  8 90 12 24 21 56 34 67]
(15,)
[[ 0  9  0  4  5]
 [ 6  7  8 90 12]
 [24 21 56 34 67]]
(3, 5)
[    0 90809     0     4     5     6     7     8    90    12    24    21
    56    34    67]
[[    0 90809     0     4     5]
 [    6     7     8    90    12]
 [   24    21    56    34    67]]
[    0 90809     0     4     5     6     7     8    90    12    24    21
    56    34    67]


In [67]:
print(arr)
for i in arr:
  print(i,end="  ")

[    0 90809     0     4     5     6     7     8    90    12    24    21
    56    34    67]
0  90809  0  4  5  6  7  8  90  12  24  21  56  34  67  

In [69]:
arr=arr.reshape(3,-1)
for i in arr:
  print(i)

[    0 90809     0     4     5]
[ 6  7  8 90 12]
[24 21 56 34 67]


In [70]:
for i in x:
  for j in i:
    print(j,end=' ')
  print()

0 90809 0 4 5 
6 7 8 90 12 
24 21 56 34 67 


In [71]:
print(arr)
for x in np.nditer(arr):
  print(x)


[[    0 90809     0     4     5]
 [    6     7     8    90    12]
 [   24    21    56    34    67]]
0
90809
0
4
5
6
7
8
90
12
24
21
56
34
67


In [72]:
print(arr)
print(arr.dtype)
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
  print(i)

[[    0 90809     0     4     5]
 [    6     7     8    90    12]
 [   24    21    56    34    67]]
int64
b'0'
b'90809'
b'0'
b'4'
b'5'
b'6'
b'7'
b'8'
b'90'
b'12'
b'24'
b'21'
b'56'
b'34'
b'67'


In [75]:
arr=np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(arr)
for x in np.nditer(arr[:,::2]):
  print(x)

[[1 2 3 4 5]
 [9 8 7 6 5]]
1
3
5
9
7
5


In [77]:
a=[1,2,3]
a=np.array(a)
print(a)
for index,val in np.ndenumerate(a):
  print(index,val)

[1 2 3]
(0,) 1
(1,) 2
(2,) 3


In [76]:
print(arr)
for i,x in np.ndenumerate(arr):
  print(i,x)

[[1 2 3 4 5]
 [9 8 7 6 5]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 9
(1, 1) 8
(1, 2) 7
(1, 3) 6
(1, 4) 5


In [78]:
a=[1,2,3]
a=np.array(a)
a=list(a)
a.append(12)
a=np.array(a)
print(a)
print(a.shape)
print(a.dtype)


[ 1  2  3 12]
(4,)
int64


In [79]:
print(a)
b=np.array([7,6,8])
print(b)
a=np.concatenate((a,b))
print(a)
print(b)

[ 1  2  3 12]
[7 6 8]
[ 1  2  3 12  7  6  8]
[7 6 8]


In [81]:
a=np.array([1,2])
print(a)
b=np.array([7,6,8])
print(b)
a=np.concatenate((b,a))
print(a)
print(b)

[1 2]
[7 6 8]
[7 6 8 1 2]
[7 6 8]


In [85]:
a=np.array([[7,6,8],[1,2,3]])
b=np.array([[9,2,7],[5,4,1]])
arr=np.concatenate((a,b))
print(arr)
abc=np.concatenate((a,b),axis=1)
print(abc)
hel=np.concatenate((a,b),axis=2)
print(hel)

[[7 6 8]
 [1 2 3]
 [9 2 7]
 [5 4 1]]
[[7 6 8 9 2 7]
 [1 2 3 5 4 1]]


AxisError: ignored